# Generated by Django 6.0.6 on 2026-06-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_note_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='text',
            new_name='content',
        ),
    ]
